version: '3.8'

services:
  api:
    build: ./api
    container_name: math-api
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGODB_URI=mongodb://mongodb:27017/math
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  # ai:
  #   build: ./apiAI
  #   container_name: math-ai
  #   restart: unless-stopped
  #   environment:
  #     - PORT=5000
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
