version: '3.8'

services:
  api:
    build: ./api
    container_name: math-api
    restart: unless-stopped
    environment:
      - PORT=4000
      - MONGODB_URI=mongodb://mongodb:27017/math
    depends_on:
      - mongodb
    networks:
      - app-network

  client:
    build: ./client
    container_name: math-client
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - api

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - api
      - site
    networks:
      - app-network

  tgbot:
    build: ./bot
    container_name: tg-bot
    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/math
      - BOT_API_PORT=4828
    depends_on:
      - mongodb
    networks:
      - app-network
    ports:
      - "4828:4828"

  site:
    build: ./site
    container_name: math-site
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
